dist: trusty
language: java
jdk:
- openjdk13

before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v

install: true

addons:
  sonarcloud:
    organization: "shockgiammy"
    token:
      secure: "4a9ef5734dac7d489d3fd8c8c7870c050a49ba03"

script:

- mvn clean javafx:compile -Pcoverage org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=ShockGiammy_WhereIGo -Dsonar.login