sudo: false
language: java
jdk:
- openjdk13

addons:
  sonarcloud:
    organization: "shockgiammy"
    token:
      secure: "16e5fb3728c133d55a6755a10058afc642b7fd0a"

before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v

install: true

script:

- mvn clean javafx:compile org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar