dist: trusty
language: java
jdk:
- openjdk11

before_install:
  - wget https://mirror.nohup.it/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v

install: true

addons:
  sonarcloud:
    organization: "shockgiammy"

install: true

script:

- mvn clean javafx:compile sonar:sonar -Pcoverage -Dsonar.projectKey=ShockGiammy_WhereIGo -Dsonar.login=$SONAR_TOKEN